on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build OHIF Viewer image via docker-compose
        run: |
          cd platform/app/.recipes/Nginx-Dcm4chee-Keycloak
          docker compose build ohif_viewer

      - name: Tag image
        run: |
          COMMIT_SHA=${{ github.sha }}
          SHORT_SHA=${COMMIT_SHA::7}
          docker tag webapp:latest etahamad/ohif-viewer:${SHORT_SHA}

      - name: Push image
        run: |
          COMMIT_SHA=${{ github.sha }}
          SHORT_SHA=${COMMIT_SHA::7}
          docker push etahamad/ohif-viewer:${SHORT_SHA}
